/**
 * Bringing the database up to the schema the running code expects.
 *
 * ### Why migrations at all, and not `drizzle-kit push`
 *
 * `push` diffs the schema against the live database and applies whatever it computes. That is a
 * reasonable development loop and the wrong thing to point at somebody else's server: the diff is
 * recomputed each time, so a column rename looks like a drop and an add, and the person who finds
 * out is the one whose data went missing. A migration is a file that was reviewed once, applied in
 * order, and recorded — which is what makes an upgrade repeatable and a rollback discussable.
 *
 * ### Why it runs at startup rather than as a deploy step
 *
 * This is a product other people install. A deploy step is a thing a self-hoster has to know about,
 * and the failure mode of not knowing is a 500 on every page with `no such table: users` in the log.
 * Running it as the database opens means `docker compose up` on a new version is the whole upgrade.
 *
 * The cost is honest: two instances starting at once would both try. SQLite serialises them — the
 * second waits on the write lock, then finds the journal already says those migrations are applied —
 * and this product is single-instance by design (one SQLite file on one disk). If it ever is not,
 * this is one of the places that has to change.
 *
 * ### Where the migration files come from
 *
 * `drizzle/`, generated by `npm run db:generate` and committed. They are read from disk at runtime
 * rather than bundled, because the migrator takes a folder; {@link MIGRATIONS} resolves it relative
 * to the process rather than to this module, since the built server is one bundled file somewhere
 * else entirely. The `Dockerfile` copies the folder into the image for exactly this reason — and
 * {@link applyMigrations} throwing when the folder is missing is better than a server that starts
 * and then fails every request.
 */

import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { log } from '../log.js';
import type { Db } from './index.js';

/**
 * Where the migration files are, relative to the working directory.
 *
 * The container's `WORKDIR` is `/app` and the folder is copied to `/app/drizzle`; in development the
 * working directory is the project root and the folder is `./drizzle`. Both resolve here.
 */
export const MIGRATIONS = 'drizzle';

/**
 * Applies every migration that has not been applied yet.
 *
 * Idempotent: Drizzle keeps a journal table and skips what is already recorded, so calling this on
 * an up-to-date database is a read.
 *
 * Throws rather than warns. A database that is not at the expected schema cannot serve requests
 * correctly, and starting anyway would turn one clear failure at boot into a different confusing
 * failure on every request.
 */
export function applyMigrations(db: Db): void {
	migrate(db, { migrationsFolder: MIGRATIONS });

	log().debug({ folder: MIGRATIONS }, 'database schema is up to date');
}
