/**
 * That the committed migrations produce the schema the code expects.
 *
 * The migration files in `drizzle/` are generated by `drizzle-kit` and committed, which means they
 * can fall behind `./schema.ts` in exactly one way nothing else notices: somebody edits the schema,
 * does not run `npm run db:generate`, and every test passes because the test suites create their
 * tables from `../fixtures/memory-db.ts` rather than from the migrations. The install that then
 * upgrades gets `no such column`.
 *
 * So this applies the real migrations to an empty database and compares the result, column by
 * column, against the fixture DDL that the rest of the suite runs on. The two have to agree, and
 * they are derived from different places: one from the committed files, one from a hand copy of the
 * schema module.
 *
 * It also covers the thing that cannot be tested anywhere else cheaply: that `applyMigrations` is
 * idempotent, since it runs on every connection open rather than as a deploy step.
 */

import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { afterEach, describe, expect, it } from 'vitest';
import { MIGRATIONS, applyMigrations } from './migrate.js';
import { memoryDb } from '../fixtures/memory-db.js';
import type { OpenMemoryDb } from '../fixtures/memory-db.js';
import * as schema from './schema.js';

/** Handles to close, whichever way the test created them. */
const opened: (() => void)[] = [];

afterEach(() => {
	for (const close of opened.splice(0)) close();
});

/** An empty database with the committed migrations applied to it. */
function migrated(): Database.Database {
	const handle = new Database(':memory:');

	opened.push(() => {
		handle.close();
	});

	applyMigrations(drizzle(handle, { schema }));

	return handle;
}

/** The fixture database the rest of the suite runs on. */
function fixture(): OpenMemoryDb {
	const open = memoryDb();

	opened.push(open.close);

	return open;
}

/** `(table, column, type, notnull, default)` for every column of every table, sorted. */
function columnsOf(rows: (sql: string) => readonly Record<string, unknown>[]): readonly string[] {
	const tables = rows(
		`SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`
	).map((row) => String(row.name));

	return tables
		.flatMap((table) =>
			rows(`PRAGMA table_info(${table})`).map(
				(column) =>
					`${table}.${String(column.name)} ${String(column.type)}` +
					` notnull=${String(column.notnull)} default=${String(column.dflt_value)}`
			)
		)
		.toSorted();
}

/** Every index, by the table and columns it covers. */
function indexesOf(rows: (sql: string) => readonly Record<string, unknown>[]): readonly string[] {
	return rows(`SELECT name, tbl_name FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL`)
		.map((row) => {
			const name = String(row.name);
			const columns = rows(`PRAGMA index_info(${name})`)
				.map((column) => String(column.name))
				.join(',');

			return `${String(row.tbl_name)}.${name} (${columns})`;
		})
		.toSorted();
}

describe('the committed migrations', () => {
	it('are where the code looks for them', () => {
		// The `Dockerfile` copies this exact path into the runtime image. If the constant changes and
		// the `COPY` does not, an upgraded container starts and then fails every request.
		expect(MIGRATIONS).toBe('drizzle');
	});

	it('create the tables the schema declares', () => {
		const present = migrated()
			.prepare(`SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`)
			.all()
			.map((row) => String((row as Record<string, unknown>).name))
			.filter((name) => !name.startsWith('__drizzle'))
			.toSorted();

		expect(present).toStrictEqual(['identities', 'sessions', 'users']);
	});

	it('produce the same columns as the fixture the suite runs on', () => {
		// Where a forgotten `npm run db:generate` is caught.
		const handle = migrated();
		const fromMigrations = columnsOf(
			(sql) => handle.prepare(sql).all() as readonly Record<string, unknown>[]
		).filter((column) => !column.startsWith('__drizzle'));

		expect(fromMigrations).toStrictEqual(columnsOf(fixture().rows));
	});

	it('produce the same indexes', () => {
		// The unique index on `(provider, provider_user_id)` is the only thing stopping two
		// simultaneous sign-ins from creating two accounts for one person. A migration missing it would
		// leave the fixture-based tests passing and production duplicating users.
		const handle = migrated();
		const fromMigrations = indexesOf(
			(sql) => handle.prepare(sql).all() as readonly Record<string, unknown>[]
		).filter((index) => !index.startsWith('__drizzle'));

		expect(fromMigrations).toStrictEqual(indexesOf(fixture().rows));
	});
});

describe('applyMigrations', () => {
	it('is idempotent, because it runs on every connection open', () => {
		const handle = migrated();

		expect(() => {
			applyMigrations(drizzle(handle, { schema }));
		}).not.toThrow();
	});

	it('leaves the tables alone when it has nothing to do', () => {
		const handle = migrated();

		handle
			.prepare('INSERT INTO users (id, name, role) VALUES (?, ?, ?)')
			.run('u', 'Someone', 'owner');
		applyMigrations(drizzle(handle, { schema }));

		expect(handle.prepare('SELECT id FROM users').all()).toStrictEqual([{ id: 'u' }]);
	});
});
